### ISSUE TITLE
Just a little code's error!

### ISSUE THREAD

**Issue by LeoBdt** [LewBr/PlanPvP-Brawl-lewbr-#5]
Your plugin didn't work at all you forgot a lot of little elements.. 
I advise you to read your plugin before posting.
:)

**Comment by LewBr** [comment]
i need any person to test this now!

**Comment by LewBr** [comment]
I stopped with this plugin because I'm doing great project in a very big server, so no need to criticize , I know I had a lot of mistakes i have only posted on github for some developers friends to have thought of the codes!
